#Install NumPy in virtual environment. Create arrays: 1D, 2D, 3D. Verify shapes.


In [35]:
import numpy as np

In [36]:
#create array
a = np.array([1,2,4,5])
print(a)

[1 2 4 5]


In [37]:
b = np.array([[5.9, 5.6, 3.2], [5.5, 6.7, 3.8]])
print(b)

[[5.9 5.6 3.2]
 [5.5 6.7 3.8]]


In [38]:
#get dimensions
a.ndim

1

In [39]:
b.ndim

2

In [40]:
#shape
b.shape

(2, 3)

In [41]:
#get datatype
a.dtype

dtype('int64')

In [42]:
#get itemsize
a.itemsize

8

In [43]:
b.itemsize

8

In [44]:
#get size
a.size

4

In [45]:
b.size

6

In [46]:
#get totalsize
b.nbytes
# or also can be written as a.size * a.itemsize

48

In [47]:
c = np.array([
    [
        [1,2,3],[3,5,6]
    ],
    [
        [3,6,7],[6,7,8]
    ]
])
print(c)

[[[1 2 3]
  [3 5 6]]

 [[3 6 7]
  [6 7 8]]]


In [48]:
c.ndim

3

In [49]:
c.shape

(2, 2, 3)

In [50]:
c.size

12

# Task 2: Broadcasting, Vectorised Operations, and Matrix Multiplication

In [9]:
#Broadcasting
salary = np.array([[45, 67, 99], [69, 34, 89]])

In [10]:
bonus = np.array([6, 9, 4])

In [11]:
new_salary = salary + bonus

In [57]:
print(new_salary)

[[ 51  76 103]
 [ 75  43  93]]


In [58]:
#also using scalar representation
new_sal = salary + 6
print(new_sal)

[[ 51  73 105]
 [ 75  40  95]]


In [62]:
#Vectorised Operations
a = np.array([2,45,67,34,78,98])

square = a ** 2
print(square)

[   4 2025 4489 1156 6084 9604]


In [65]:
double = a * 2
add = a + 2
sub = a - 1
div = a/2

In [66]:
print(double)
print(add)
print(sub)
print(div)

[  4  90 134  68 156 196]
[  4  47  69  36  80 100]
[ 1 44 66 33 77 97]
[ 1.  22.5 33.5 17.  39.  49. ]


In [4]:
#Matrix Multiplication
m = np.array([
    [1,3],
    [1,5]
])

n = np.array([
    [2,4],
    [4,5]
])

q = np.full([2,3], 2)
result = m * n
print(result)
print(q)

[[ 2 12]
 [ 4 25]]
[[2 2 2]
 [2 2 2]]


In [5]:
res = m @ n
print(res)

np.matmul(m,q)

[[14 19]
 [22 29]]


array([[ 8,  8,  8],
       [12, 12, 12]])

# Task 3: Statistics on a CSV Dataset

In [47]:
from pathlib import Path

In [12]:
stats = np.array([[2,4,6],[3,5,7]])
stats

array([[2, 4, 6],
       [3, 5, 7]])

In [21]:
np.max(stats, axis = 1)

array([6, 7])

In [20]:
np.min(stats, axis = 0)

array([2, 4, 6])

In [22]:
before = np.array([[1,3,4,5],[2,5,6,7]])
before

array([[1, 3, 4, 5],
       [2, 5, 6, 7]])

In [23]:
before.shape

(2, 4)

In [27]:
after = before.reshape(4,2)

In [28]:
after

array([[1, 3],
       [4, 5],
       [2, 5],
       [6, 7]])

In [31]:
aft = before.reshape(8,1)

In [32]:
aft

array([[1],
       [3],
       [4],
       [5],
       [2],
       [5],
       [6],
       [7]])

In [68]:
#Mean of the array
a1 = np.array([12,4,45,5,462,12,4,35])
res1 = np.mean(a1)
print(res1)

72.375


In [69]:
#Standard Deviation of the Array
res2 = np.std(a1)
print(res2)

147.95855627505966


In [67]:
#Correlation on real csv dataset
file_path = Path("../data/data.csv")
data = np.genfromtxt(file_path, delimiter = ',')
print(data)

[[ 5. 75.  8.]
 [ 7. 85.  7.]
 [ 3. 60.  9.]
 [ 8. 92.  6.]
 [ 6. 80.  8.]]


In [66]:
cor = np.corrcoef(data, rowvar=False)
cor = cor.astype('int32')
print(cor)

[[1 0 0]
 [0 1 0]
 [0 0 1]]
