In [1]:
import numpy as np

In [19]:
#create array
a = np.array([1,2,4,5])
print(a)

[1 2 4 5]


In [4]:
b = np.array([[5.9, 5.6, 3.2], [5.5, 6.7, 3.8]])
print(b)

[[5.9 5.6 3.2]
 [5.5 6.7 3.8]]


In [10]:
#get dimensions
a.ndim

1

In [11]:
b.ndim

2

In [12]:
#shape
b.shape

(2, 3)

In [20]:
#get datatype
a.dtype

dtype('int64')

In [21]:
#get itemsize
a.itemsize

8

In [22]:
b.itemsize

8

In [25]:
#get size
a.size

4

In [24]:
b.size

6

In [27]:
#get totalsize
b.nbytes
# or also can be written as a.size * a.itemsize

48

In [28]:
c = np.array([
    [
        [1,2,3],[3,5,6]
    ],
    [
        [3,6,7],[6,7,8]
    ]
])
print(c)

[[[1 2 3]
  [3 5 6]]

 [[3 6 7]
  [6 7 8]]]


In [29]:
c.ndim

3

In [30]:
c.shape

(2, 2, 3)

In [31]:
c.size

12